// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/29/2024, 1:27:07 PM
const configMerger = require("/home/dreamworld/PrecticeProject/villing-movie/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {
    "content": [], "theme": {
        "extend": {
            colors: {
                brown: '#621E06',
            },
        }
    }, "plugins": []
};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/dreamworld/PrecticeProject/villing-movie/components/**/*.{vue,js,jsx,mjs,ts,tsx}", "/home/dreamworld/PrecticeProject/villing-movie/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}", "/home/dreamworld/PrecticeProject/villing-movie/components/**/*.{vue,js,jsx,mjs,ts,tsx}", "/home/dreamworld/PrecticeProject/villing-movie/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}", "/home/dreamworld/PrecticeProject/villing-movie/pages/**/*.{vue,js,jsx,mjs,ts,tsx}", "/home/dreamworld/PrecticeProject/villing-movie/plugins/**/*.{js,ts,mjs}", "/home/dreamworld/PrecticeProject/villing-movie/composables/**/*.{js,ts,mjs}", "/home/dreamworld/PrecticeProject/villing-movie/utils/**/*.{js,ts,mjs}", "/home/dreamworld/PrecticeProject/villing-movie/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}", "/home/dreamworld/PrecticeProject/villing-movie/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}", "/home/dreamworld/PrecticeProject/villing-movie/app.config.{js,ts,mjs}"] }));

module.exports = config
