// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/29/2024, 1:27:07 PM
const configMerger = require("./node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {
    "content": [], "theme": {
        "extend": {
            colors: {
                brown: '#621E06',
                lightgreen: '#9BC05B',
            },
        }
    }, "plugins": []
};

const config = [
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["./components/**/*.{vue,js,jsx,mjs,ts,tsx}", "./components/global/**/*.{vue,js,jsx,mjs,ts,tsx}", "./marketplace/components/**/*.{vue,js,jsx,mjs,ts,tsx}", "./layouts/**/*.{vue,js,jsx,mjs,ts,tsx}", "./pages/**/*.{vue,js,jsx,mjs,ts,tsx}", "./plugins/**/*.{js,ts,mjs}", "./composables/**/*.{js,ts,mjs}", "./utils/**/*.{js,ts,mjs}", "./{A,a}pp.{vue,js,jsx,mjs,ts,tsx}", "./{E,e}rror.{vue,js,jsx,mjs,ts,tsx}", "./app.config.{js,ts,mjs}"] }));

module.exports = config
