// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/29/2024, 1:27:07 PM
const configMerger = require("/Sunil Sarvaiya/Nuxt js/marketplace/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {
    "content": [], "theme": {
        "extend": {
            colors: {
                brown: '#621E06',
            },
        }
    }, "plugins": []
};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Sunil Sarvaiya/Nuxt js/marketplace/components/**/*.{vue,js,jsx,mjs,ts,tsx}", "/Sunil Sarvaiya/Nuxt js/marketplace/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}", "/Sunil Sarvaiya/Nuxt js/marketplace/components/**/*.{vue,js,jsx,mjs,ts,tsx}", "/Sunil Sarvaiya/Nuxt js/marketplace/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}", "/Sunil Sarvaiya/Nuxt js/marketplace/pages/**/*.{vue,js,jsx,mjs,ts,tsx}", "/Sunil Sarvaiya/Nuxt js/marketplace/plugins/**/*.{js,ts,mjs}", "/Sunil Sarvaiya/Nuxt js/marketplace/composables/**/*.{js,ts,mjs}", "/Sunil Sarvaiya/Nuxt js/marketplace/utils/**/*.{js,ts,mjs}", "/Sunil Sarvaiya/Nuxt js/marketplace/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}", "/Sunil Sarvaiya/Nuxt js/marketplace/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}", "/Sunil Sarvaiya/Nuxt js/marketplace/app.config.{js,ts,mjs}"] }));

module.exports = config
